
PROVIDER = "vmware_desktop"
Vagrant.configure("2") do |config|

  # I choosed centos/7 because this version will be maintained until 2024
  config.vm.box = "centos/7"
  config.vm.boot_timeout = 1000

  # This configurations is shared between the two next configurations
  config.vm.provider PROVIDER do |v|
    v.gui = true
    v.memory = '1024'
    v.cpus = '2'
  end

  MASTER_NAME = "mamauraiS"
  config.vm.define MASTER_NAME do |m|
    m.vm.hostname = MASTER_NAME
    m.vm.network "private_network", ip: "192.168.56.110"
    # m.vm.provider PROVIDER do |v|
    #   v.name = MASTER_NAME
    # end
  end
  
  WORKER_NAME = "mamauraiSW"
  config.vm.define WORKER_NAME do |m|
    m.vm.hostname = WORKER_NAME
    m.vm.network "private_network", ip: "192.168.56.111"
    #m.vm.provider PROVIDER do |v|
    #  v.name = WORKER_NAME
    #end
  end
end
  
