Vagrant.configure("2") do |config|

  config.vm.define "mamaurai" do |m|
    m.vm.box = ""
    m.vm.hostname = "mamauraiS"
    m.vm.network "private_network", ip: "192.168.56.110"
    m.vm.provider "virtualbox" do |d|
      d.name = "mamaurai"
      d.memory = "512"
      d.cpus = "1"
    end
    config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/ChallengeR sponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    service ssh restart
    SHELL
  end


  config.vm.define "mamaurai" do |m|
    m.vm.box = ""
    m.vm.hostname = "mamauraiSW"
    m.vm.network "private_network", ip: "192.168.56.111"
    m.vm.provider "virtualbox" do |d|
      d.name = "mamaurai"
      d.memory = "512"
      d.cpus = "1"
    end
    config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/ChallengeR sponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    service ssh restart
    SHELL
  end
end
