# use the version 2 of Vagrant and use config to configure the cluster
Vagrant.configure("2") do |config|

  # create vm named kmaster with value kmaster to configure this vm
  config.vm.define "kmaster" do |kmaster|
    # box is a Vagrant cloud box
    kmaster.vm.box = "debian/stretch64"
    kmaster.vm.hostname = "kmaster"
    kmaster.vm.box_url = "debian/stretch64"
    kmaster.vm.network :private_network, ip: "192.168.100.10"
    kmaster.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", ":id", "--natdnshostsolver1", "on"]
      v.customize ["modifyvm", ":id", "--memory", 2048]
      v.customize ["modifyvm", ":id", "--name", "kmaster"]
      v.customize ["modifyvm", ":id", "--cpus", "2"]
    end
  end
end

